#' Extract index data
#'
#' Subsets area weights and extracts n values from JAGS samples
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#'
#' @importFrom utils read.csv
#' @importFrom posterior as_draws_list
#'
#' @return List of index values produced by JAGS samples
#'
#' @keywords internal
#' @export
#'

extract_index_data <- function(jags_mod = NULL,
                               alt_n = "n",
                               jags_data = NULL,
                               stratify_by = NULL,
                               backend = NULL)
{

  source("functions/posterior_summary_functions.R")
  
  if(is.null(backend))
  {
    if(any(grepl("jags",class(jags_mod)))){
      backend <- "JAGS"
    }else{
      backend <- "Stan"
    }
  }
  # Read area weights
  if(is.null(stratify_by))
  {
    stratify_by <- jags_mod$stratify_by
  }
  

  strata <- list(bcr = "bcr",
                 latlong = "db",
                 state = "stateprov",
                 bbs_usgs = "strat",
                 bbs_cws = "stratcan")
  
  all_area_weights <- utils::read.csv(paste0(system.file("area-weight", package = "bbsBayes"),"/",strata[[stratify_by]],".csv"))

  # Extract posterior data and other data from jags_mod
  if(backend == "JAGS"){
  n <- jags_mod$sims.list[[alt_n]]
  if (isTRUE(jags_mod$parallel))
  {
    bugs_data <- jags_mod$model$cluster1$data()
  }else
  {
    bugs_data <- jags_mod$model$data()
  }
  y_min <- bugs_data$ymin
  y_max <- bugs_data$ymax
  }
  if(backend == "Stan"){
    out_list <- jags_mod$draws(format = "draws_matrix",
                                         variables = alt_n)
    n <- array(data = NA,dim = c(nrow(out_list),jags_data$nstrata,jags_data$nyears))
    for(i in 1:jags_data$nstrata){
      for(j in 1:jags_data$nyears)
      n[,i,j] <- as.numeric((out_list[,paste0(alt_n,"[",i,",",j,"]")]))
    }

    bugs_data <- jags_data

    y_min <- 1
    y_max <- bugs_data$nyears

# extract observer and route estimates ------------------------------------
  sd_ste <- posterior_samples(jags_mod,
                              parm = "sdste") %>% 
    select(.draw,.value) %>% 
    rename(sdste = .value)
  
  ste_list <- posterior_samples(jags_mod,
                                parm = "ste_raw",
                                dims = c("site")) %>% 
    left_join(.,sd_ste,by = ".draw") %>% 
    mutate(.value = .value*sdste) %>% 
    posterior_sums(.,dims = c("site")) %>% 
    select(site,mean) %>% 
    rename(ste = mean)
      
  
  sd_obs <- posterior_samples(jags_mod,
                              parm = "sdobs") %>% 
    select(.draw,.value) %>% 
    rename(sdobs = .value)
  
  obs_list <- posterior_samples(jags_mod,
                                parm = "obs_raw",
                                dims = c("observer")) %>% 
    left_join(.,sd_obs,by = ".draw") %>% 
    mutate(.value = .value*sdobs) %>% 
    posterior_sums(.,dims = c("observer")) %>% 
    select(observer,mean) %>% 
    rename(obs = mean)
  
  surveys <- data.frame(site = bugs_data$site,
                        observer = bugs_data$observer,
                        strat = bugs_data$strat,
                        year = bugs_data$year) %>% 
    left_join(.,obs_list,by = "observer") %>% 
    left_join(.,ste_list,by = "site")
  
  annual_means <- surveys %>% 
    group_by(year,strat) %>% 
    summarise(mean_site = mean(ste),
              mean_obs = mean(obs),
              e_site = exp(mean_site),
              e_obs = exp(mean_obs),
              re_scale = e_site*e_obs,
              .groups = "keep")
  
  }



### after fitting Stan models, reattach the missing bits to the data-list
  strat_list = unique(data.frame(strat_name = jags_data$strat_name,
                          strat = bugs_data$strat,
                          stringsAsFactors = FALSE))
  strat_list = strat_list[order(strat_list$strat),]

  # Subset area weights based on strata used and ensure same order as JAGS
  strata_used <- strat_list$strat_name
  strata_num <- strat_list$strat
  area_weights <- all_area_weights[which(all_area_weights$region %in% strata_used), ]
  area_weights <- area_weights[ order(match(area_weights$region, strata_used)),]
  area_weights$num <- strata_num

  if(!is.null(jags_data)){
    if(backend == "JAGS"){
    original_data = get_prepared_data(jags_data = jags_data)
    }
    if(backend == "Stan"){
      original_data = jags_data$alt_data[[1]][,c("rYear",
                                                 "year",
                                                 "count",
                                                 "strat_name",
                                                 "strat",
                                                 "observer",
                                                 "site",
                                                 "firstyr")]
      names(original_data) <- c("Year","Year_Factored","Count","Stratum","Stratum_Factored","Observer_Factored","Route","First_Year")


    }
  }else{
    original_data = NULL
  }
  return(list(n = n,
              annual_means = annual_means,
              area_weights = area_weights,
              y_min = y_min,
              y_max = y_max,
              r_year = jags_data$r_year,
              bugs_data = bugs_data,
              original_data = original_data,
              stratify_by = stratify_by))
}
